CREATE TABLE STOCK_DATA (
	STOCK_DATA_ID VARCHAR(20) NOT NULL,
	DATE DATE NOT NULL,
	STOCK_SYMBOL VARCHAR(10) NOT NULL,
	OPEN DECIMAL(20,4) NOT NULL,
	HIGH DECIMAL(20,4) NOT NULL,
	LOW DECIMAL(20,4) NOT NULL,
	CLOSE DECIMAL(20,4) NOT NULL,
	VOLUME DECIMAL(20,0) NOT NULL,
	LOCAL_MAX_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (STOCK_DATA_ID)
);

CREATE TABLE SPLIT_DATA (
	DATE DATE NOT NULL,
	STOCK_SYMBOL VARCHAR(10) NOT NULL,
	SPLIT_FACTOR DECIMAL(10,4) NOT NULL,
	PRIMARY KEY (DATE, STOCK_SYMBOL)
);