create or replace TABLE MARKETDATA.PUBLIC.STOCK_DATA (
	DATE DATE NOT NULL,
	STOCK_SYMBOL VARCHAR(10) NOT NULL,
	OPEN NUMBER(38,0) NOT NULL,
	HIGH NUMBER(38,0) NOT NULL,
	LOW NUMBER(38,0) NOT NULL,
	CLOSE NUMBER(38,0) NOT NULL,
	VOLUME NUMBER(38,0) NOT NULL,
	LOCAL_MAX NUMBER(38,0) NOT NULL,
	primary key (DATE, STOCK_SYMBOL)
);

-- primary key doesn't do anything in snowflake sadge :(