create or replace TABLE MARKETDATA.PUBLIC.STOCK_DATA (
	STOCK_DATA_ID VARCHAR(20) NOT NULL,
	DATE DATE NOT NULL,
	STOCK_SYMBOL VARCHAR(10) NOT NULL,
	OPEN NUMBER(20,4) NOT NULL,
	HIGH NUMBER(20,4) NOT NULL,
	LOW NUMBER(20,4) NOT NULL,
	CLOSE NUMBER(20,4) NOT NULL,
	VOLUME NUMBER(20,0) NOT NULL,
	LOCAL_MAX_ID VARCHAR(20) NOT NULL
);